import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from"@/components/layout/Navbar";
import SocialSidebar from "@/components/layout/SocialSidebar";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-screen bg-[#2b2d3a] text-slate-100`}
      >
        <Navbar/>
        <SocialSidebar />
        {children}
      </body>
    </html>
  );
}
